# Generated by Django 5.0.4 on 2024-05-10 00:20

import apps.users.models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearcherUser",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_column="uuid",
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        db_column="address", max_length=90, unique=True
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        db_column="phone_number",
                        max_length=25,
                        region=None,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "searcher_user",
                "verbose_name_plural": "searcher_users",
                "db_table": "searcher_user",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_column="uuid",
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(db_column="full_name", max_length=60),
                ),
                (
                    "email",
                    models.EmailField(
                        db_column="email",
                        db_index=True,
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "password",
                    models.CharField(db_column="password", max_length=128),
                ),
                (
                    "profile",
                    models.UUIDField(
                        db_column="profile",
                        db_index=True,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(db_column="is_staff", default=False),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        db_column="is_superuser", default=False
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_column="is_active", db_index=True, default=False
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(db_column="last_login", null=True),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, db_column="date_joined"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        db_column="content_type",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "user",
                "ordering": ["is_active", "-date_joined"],
            },
            managers=[
                ("objects", apps.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="JWT",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_column="uuid",
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "jti",
                    models.CharField(
                        db_column="jti",
                        db_index=True,
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("token", models.TextField(db_column="token")),
                ("expires_at", models.DateTimeField(db_column="expires_at")),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, db_column="date_joined"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "JWT",
                "verbose_name_plural": "JWT's",
                "db_table": "jwt",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="JWTBlacklist",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_column="uuid",
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, db_column="date_joined"
                    ),
                ),
                (
                    "token",
                    models.OneToOneField(
                        db_column="token_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.jwt",
                    ),
                ),
            ],
            options={
                "verbose_name": "JWT_blacklist",
                "verbose_name_plural": "JWT_blacklist",
                "db_table": "jwt_blacklist",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email", "is_active"], name="email_is_active_idx"
            ),
        ),
    ]
