# Generated by Django 5.0.6 on 2024-08-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="token",
            table=None,
        ),
    ]
