# Generated by Django 5.0.6 on 2024-05-22 23:45

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searcheruser",
            name="address",
            field=models.CharField(
                blank=True,
                db_column="address",
                max_length=90,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="searcheruser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                db_column="phone_number",
                max_length=25,
                null=True,
                region=None,
                unique=True,
            ),
        ),
    ]
