# Generated by Django 5.1.1 on 2024-09-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_baseuser_options_alter_searcher_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseuser",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_column="deleted_at", null=True
            ),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="last_login",
            field=models.DateTimeField(
                blank=True, db_column="last_login", null=True
            ),
        ),
    ]
