# Generated by Django 5.1.1 on 2024-09-17 15:08

import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0004_alter_baseuser_deleted_at_alter_baseuser_last_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealEstateEntity",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_column="uuid",
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_entity",
                    models.CharField(
                        choices=[
                            ("realestate", "realestate"),
                            ("constructioncompany", "constructioncompany"),
                        ],
                        db_column="type_entity",
                        max_length=40,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="name",
                        db_index=True,
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(db_column="description", max_length=400),
                ),
                (
                    "nit",
                    models.CharField(
                        db_column="nit",
                        db_index=True,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "phone_numbers",
                    models.CharField(
                        db_column="phone_numbers", db_index=True, max_length=39
                    ),
                ),
                (
                    "department",
                    models.CharField(db_column="department", max_length=25),
                ),
                (
                    "municipality",
                    models.CharField(db_column="municipality", max_length=25),
                ),
                ("region", models.CharField(db_column="region", max_length=80)),
                (
                    "coordinate",
                    models.CharField(
                        db_column="coordinate",
                        db_index=True,
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "is_phones_verified",
                    models.JSONField(db_column="is_phones_verified"),
                ),
                (
                    "communication_channels",
                    models.JSONField(db_column="communication_channels"),
                ),
                ("documents", models.JSONField(db_column="documents")),
                (
                    "verified",
                    models.BooleanField(db_column="verified", default=False),
                ),
            ],
            options={
                "verbose_name": "Real Estate Entity",
                "verbose_name_plural": "Real Estate Entities",
            },
        ),
        migrations.AlterModelOptions(
            name="searcher",
            options={
                "verbose_name": "Searcher",
                "verbose_name_plural": "Searchers",
            },
        ),
        migrations.RemoveField(
            model_name="searcher",
            name="address",
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="email",
            field=models.EmailField(
                db_column="email", db_index=True, max_length=40, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="searcher",
            name="cc",
            field=models.CharField(
                blank=True,
                db_column="cc",
                db_index=True,
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="searcher",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                db_column="phone_number",
                db_index=True,
                max_length=19,
                null=True,
                region=None,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="baseuser",
            index=models.Index(
                fields=["uuid", "is_active"], name="users_baseu_uuid_c1d390_idx"
            ),
        ),
    ]
