# Generated by Django 5.1.1 on 2024-09-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_realestateentity_alter_searcher_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseuser",
            name="is_active",
            field=models.BooleanField(db_column="is_active"),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="is_deleted",
            field=models.BooleanField(db_column="is_deleted"),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="is_staff",
            field=models.BooleanField(db_column="is_staff"),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="is_superuser",
            field=models.BooleanField(db_column="is_superuser"),
        ),
        migrations.AlterField(
            model_name="realestateentity",
            name="communication_channels",
            field=models.JSONField(
                blank=True, db_column="communication_channels", null=True
            ),
        ),
        migrations.AlterField(
            model_name="realestateentity",
            name="documents",
            field=models.JSONField(
                blank=True, db_column="documents", null=True
            ),
        ),
        migrations.AlterField(
            model_name="realestateentity",
            name="verified",
            field=models.BooleanField(db_column="verified"),
        ),
        migrations.AlterField(
            model_name="searcher",
            name="is_phone_verified",
            field=models.BooleanField(db_column="is_phone_verified"),
        ),
    ]
