# Generated by Django 5.1.1 on 2024-09-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0006_alter_baseuser_is_active_alter_baseuser_is_deleted_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseuser",
            name="is_active",
            field=models.BooleanField(db_column="is_active", default=False),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="is_deleted",
            field=models.BooleanField(db_column="is_deleted", default=False),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="is_staff",
            field=models.BooleanField(db_column="is_staff", default=False),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="is_superuser",
            field=models.BooleanField(db_column="is_superuser", default=False),
        ),
    ]
